spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070
eureka:
#   instance:
#     hostname: eurekaserver
  # instance:
  #   instance-id: ${spring.cloud.client.ip-address}:${server.port}
  #   preferIpAddress: true
    hostname: localhost
    # hostname: ${spring.cloud.client.ip-address}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
# eureka:
#  instance:
#    hostname: localhost
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl: 
#      defaultZone: http://localhost:8070/eureka/
#      # defaultZone: http://eureka-server:8070/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 5
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
