server:
  port: 8072
  address: 0.0.0.0
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://eurekaserver:8070/eureka/
      defaultZone: http://localhost:8070/eureka/


# 
eureka.instance.hostname: localhost
eureka.instance.instanceId: ${eureka.instance.hostname}:${server.port}
# 
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
      - id: licensing-service
        uri: lb://licensing-service
        predicates:
        - Path=/license/**
        - Before=2023-11-06T18:38:27.408396900+03:00[Europe/Moscow]
        filters:
        - RewritePath=/license/(?<path>.*), /$\{path}
        - SetStatus=202
        - SetResponseHeader=X-My-ID,123
      - id: request_rate_limiter
        uri: lb://licensing-service
        predicates:
        - Path=/license/**
        filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
            redis-rate-limiter.remaining: 1
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@userKeyResolver}"
      # - id: golden_route
      #   uri: lb://licensing-service
      #   predicates:
      #   - Path=/license/**
      #   # - GoldenCustomer=true
      #   - name: GoldenCustomer
      #     args:
      #       isGolden: true
      #       customerIdCookie: customerId
      #   filters:
      #   - StripPrefix=1
      #   - AddRequestHeader=GoldenCustomer,true
      # - id: common_route
      #   uri: lb://licensing-service-slower
      #   predicates:
      #   - Path=/license/**
      #   - name: GoldenCustomer
      #     args:
      #       isGolden: false
      #       customerIdCookie: customerId
      #   filters:
      #   - StripPrefix=1
      #   - AddRequestHeader=GoldenCustomer,false
       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
